export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const POST_ORDER_REQUEST = 'POST_ORDER_REQUEST';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAILURE = 'POST_ORDER_FAILURE';

export const POST_ORDER_INFO_REQUEST = 'POST_ORDER_INFO_REQUEST';
export const POST_ORDER_INFO_SUCCESS = 'POST_ORDER_INFO_SUCCESS';
export const POST_ORDER_INFOFAILURE = 'POST_ORDER_INFO_FAILURE';

export const ADD_PRODUCT_AMOUNT = 'ADD_PRODUCT_AMOUNT';
export const SUB_PRODUCT_AMOUNT  = 'SUB_PRODUCT_AMOUNT';
export const CHANGE_PRODUCT_AMOUNT  = 'CHANGE_PRODUCT_AMOUNT';